// pages/_document.js

import Document, { Html, Head, Main, NextScript } from 'next/document'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default class MyDocument extends Document {
  render () {
    return (
      <Html lang='en'>
        <Head>
          {/* Place your meta tags and other head elements here */}
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <meta name='description' content='Generated by create next app' />
          {/* Include any other meta tags and CSS or fonts here */}
        </Head>
        <body className={inter.className}>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
